---
version: 1
git_protocol: https
editor: code --wait
prompt: enabled
prefer_editor_prompt: disabled
pager: cat
aliases:
  co: pr checkout
  prs: search prs --state open --owner @me
http_unix_socket:
browser:
